# use by...
# $ pinact run
# $ pinact --config ../Actions/.pinact.yaml run
version: 3
ignore_actions:
  - name: guitarrapc/actions/.*
    ref: main
  - name: guitarrapc/githubactions-lab/.*
    ref: main
