name: Setup .NET SDKs
description: Setup .NET SDKs and environment variables
inputs:
  dotnet-version:
    description: "Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x"
    required: false
    default: "6.0"
  dotnet-quality:
    description: "Optional quality of the build. The possible values are: daily, signed, validated, preview, ga."
    required: false
    default: ga
  restore-wasm-workload:
    description: "Restore wasm workload"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        dotnet-quality: ${{ inputs.dotnet-quality }}

    - name: "Configure Environment Variables (.NET SDK)"
      shell: bash
      run: |
        echo "::group::Configure .NET Environment Variables."
          echo "MSBUILDDISABLENODEREUSE=1" | tee -a "$GITHUB_ENV"
          echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" | tee -a "$GITHUB_ENV"
          echo "DOTNET_NOLOGO=1" | tee -a "$GITHUB_ENV"
          echo "DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1" | tee -a "$GITHUB_ENV"
          echo "NUGET_XMLDOC_MODE=skip" | tee -a "$GITHUB_ENV"
          echo "DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION=1" | tee -a "$GITHUB_ENV"
          echo "TERM=xterm" | tee -a "$GITHUB_ENV"
        echo "::endgroup::"

    - name: Install Wasm workload
      shell: bash
      run: |
        echo "::group::Install wasm workload if needed."
          if [[ "${{ inputs.restore-wasm-workload }}" == "true" ]]; then
            dotnet workload install wasm-tools
            if [[ "${{ inputs.dotnet-version }}" == "7.0.x" ]]; then
              dotnet workload install wasm-tools-net6
            fi
          else
            echo "no need install wasm-tools workload"
          fi
        echo "::endgroup::"

    - name: dotnet verseion
      shell: bash
      run: |
        echo "::group::Show dotnet version"
          dotnet --version
        echo "::endgroup::"

    - name: List installed .NET SDKs
      shell: bash
      run: |
        echo "::group::List installed dotnet sdks"
          dotnet --list-sdks
        echo "::endgroup::"
