name: actionlint oss

# Instructions:
# * This workflow is for checking the actionlint and ghalint public repositories.
# * If any errors are found, "fix each repository" or "ignore error".
# * fix each repository: Check repository workflow and fix it.
# * ignore error: ignore config is located in guitarrapc/actions repository. Add ignore to .github/actionlint.yaml or .ghalint.yaml, depends on the error.

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * WED" # every wednesday 10:00 +9(JST)

jobs:
  actionlint:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      # gh repo list guitarrapc --visibility public --no-archived --json name
      - name: List non-archived OSS Repository names as json array
        id: list
        run: gh repo list ${{ github.repository_owner }} --visibility public --no-archived --json name --jq 'sort_by(.name | ascii_downcase) | .[].name' > ${{ github.workspace }}/repositories.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.51.2
      - name: Clone repositories
        run: |
          for repository in $(cat "${{ github.workspace }}/repositories.txt"); do
            echo "repository=${repository}" | tee -a "$GITHUB_ENV"
            git clone --depth 1 "${{ github.repository_owner }}/${repository}" "${repository}""
          done
      # github workflows/action's Static Checker
      - name: Run actionlint
        run: |
          for repository in $(cat "${{ github.workspace }}/repositories.txt"); do
            pushd "${repository}"
              actionlint -color -oneline --config-file ../.github/actionlint.yaml
            popd
          done
      # checkout's persist-credentials: false checker
      - name: Run ghalint
        run: |
          for repository in $(cat "${{ github.workspace }}/repositories.txt"); do
            pushd "${repository}"
              ghalint -c ../.ghalint.yaml run
            popd
          done
      - name: Run ghalint
        run: |
          for repository in $(cat "${{ github.workspace }}/repositories.txt"); do
            pushd "${repository}"
              ghalint -c ../.ghalint.yaml run-action
            popd
          done
