name: actionlint oss

# Instructions:
# * This workflow is for checking the actionlint and ghalint public repositories.
# * If any errors are found, "fix each repository" or "ignore error".
# * fix each repository: Check repository workflow and fix it.
# * ignore error: ignore config is located in guitarrapc/actions repository. Add ignore to .github/actionlint.yaml or .ghalint.yaml, depends on the error.

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * WED" # every wednesday 10:00 +9(JST)

jobs:
  pre:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    outputs:
      repositories: ${{ steps.list.outputs.repositories }}
    steps:
      # gh repo list guitarrapc --visibility public --no-archived --json name
      # except "blog" repository
      - name: List non-archived OSS Repository names as json array
        id: list
        run: echo "repositories=$(gh repo list ${{ github.repository_owner }} --visibility public --no-archived --json name --jq 'sort_by(.name | ascii_downcase) | map(select(.name != "blog")) | .[].name' | jq -R -s -c 'split("\n")[:-1]')" | tee -a "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Try json parse (Should output as Array)
        run: echo "${{ fromJson(steps.list.outputs.repositories) }}"

  actionlint:
    needs: [pre]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        repository: ${{ fromJson(needs.pre.outputs.repositories) }}
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        with:
          aqua_version: v2.43.1
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
          repository: "${{ github.repository_owner }}/${{ matrix.repository }}"
          path: ${{ matrix.repository }}
      # github workflows/action's Static Checker
      - name: Run actionlint
        run: |
          if [[ -f .github/actionlint.yaml ]]; then
            actionlint -color -oneline
          else
            actionlint -color -oneline --config-file ../.github/actionlint.yaml
          fi
        working-directory: ${{ matrix.repository }}
      # checkout's persist-credentials: false checker
      - name: Run ghalint
        run: |
          if [[ -f .ghalint.yaml ]]; then
            ghalint run
          else
            ghalint -c ../.ghalint.yaml run
          fi
        working-directory: ${{ matrix.repository }}
      - name: Run ghalint
        run: |
          if [[ -f .ghalint.yaml ]]; then
            ghalint run-action
          else
            ghalint -c ../.ghalint.yaml run-action
          fi
        working-directory: ${{ matrix.repository }}
