name: (R) dotnet lint

on:
  workflow_call:
    inputs:
      sln-root:
        default: "."
        description: .sln root to execute dotnet-format
        required: false
        type: string
      dotnet-version:
        default: 6.0.x
        description: dotnet-version to use
        required: false
        type: string
      base-branch:
        default: "main"
        description: base branch to create PR
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Prepare .NET
        uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          restore-wasm-workload: "true"

      # dotnet list
      - name: Obtain csproj to lint
        run: |
          projects=$(dotnet sln list | tail -n +3)
          format_projects=$(echo "$projects" | sort | xargs -n 1 echo '  *')

          {
            echo "PROJECTS<<EOF"
            echo "${projects}"
            echo "EOF"
          } >> "$GITHUB_ENV"
          {
            echo "FORMAT_PROJECTS<<EOF"
            echo "${format_projects}"
            echo "EOF"
          } >> "$GITHUB_ENV"
        working-directory: ${{ inputs.sln-root }}

      # dotnet format is build-in from dotnet 6.0 sdk
      - name: Dotnet Format
        run: |
          echo "${{ env.PROJECTS }}" | while IFS= read -r csproj; do
            dotnet format "$csproj" --verbosity diagnostic --exclude "console-fail-tests"
          done
        working-directory: ${{ inputs.sln-root }}

      # is change happen?
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> "$GITHUB_OUTPUT"

      # get directory stats
      - name: List modified directories
        if: steps.git-check.outputs.modified == 'true'
        run: |
          dirs=$(git diff --dirstat=files)
          {
            echo "CHANGED_DIRS<<EOF"
            echo "${dirs}"
            echo "EOF"
          } >> "$GITHUB_ENV"

      # get files stats
      - name: List modified files
        if: steps.git-check.outputs.modified == 'true'
        run: |
          files=$(git diff --name-only)
          {
            echo "CHANGED_FILES<<EOF"
            echo "${files}"
            echo "EOF"
          } >> "$GITHUB_ENV"

      # Commit if change happen, then craete PR. force push when branch/pr already exists.
      - name: Create PullRequest
        if: steps.git-check.outputs.modified == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          base: "${{ inputs.base-branch }}"
          branch: "auto-pr/dotnet-format"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          delete-branch: true
          commit-message: "[dotnet format] Automated changes"
          title: "[dotnet format] Automated changes"
          body: |
            ## tl;dr;
            dotnet format generated changes based on .editorconfig

            ## Stats

            changed directories

            ```
            ${{ env.CHANGED_DIRS }}
            ```

            ## Files

            <details>
            <summary>Click to show.</summary>

            ```
            ${{ env.CHANGED_FILES }}
            ```

            </details>

            ## Target Projects

            ${{ env.FORMAT_PROJECTS }}

          labels: |
            automated pr

      - name: Check outputs
        if: steps.git-check.outputs.modified == 'true'
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
